POST http://localhost:3000/api/accountType
content-type: application/json

{
    "code": "12",
    "name": "Kusuma Tbk 232"
}
###Fix
GET http://localhost:3000/api/generate/sampahCategory?rows=10
###
GET http://localhost:3000/api/generate/sampahType?rows=30